/*
 * This file is generated by jOOQ.
 */
package com.epam.ta.reportportal.jooq.tables.records;


import com.epam.ta.reportportal.jooq.tables.JAttachment;

import java.sql.Timestamp;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JAttachmentRecord extends UpdatableRecordImpl<JAttachmentRecord> implements Record9<Long, String, String, String, Long, Long, Long, Long, Timestamp> {

    private static final long serialVersionUID = 171693268;

    /**
     * Setter for <code>public.attachment.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.attachment.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.attachment.file_id</code>.
     */
    public void setFileId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.attachment.file_id</code>.
     */
    public String getFileId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.attachment.thumbnail_id</code>.
     */
    public void setThumbnailId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.attachment.thumbnail_id</code>.
     */
    public String getThumbnailId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.attachment.content_type</code>.
     */
    public void setContentType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.attachment.content_type</code>.
     */
    public String getContentType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.attachment.project_id</code>.
     */
    public void setProjectId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.attachment.project_id</code>.
     */
    public Long getProjectId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.attachment.launch_id</code>.
     */
    public void setLaunchId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.attachment.launch_id</code>.
     */
    public Long getLaunchId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.attachment.item_id</code>.
     */
    public void setItemId(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.attachment.item_id</code>.
     */
    public Long getItemId() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>public.attachment.file_size</code>.
     */
    public void setFileSize(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.attachment.file_size</code>.
     */
    public Long getFileSize() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>public.attachment.creation_date</code>.
     */
    public void setCreationDate(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.attachment.creation_date</code>.
     */
    public Timestamp getCreationDate() {
        return (Timestamp) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Long, String, String, String, Long, Long, Long, Long, Timestamp> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Long, String, String, String, Long, Long, Long, Long, Timestamp> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return JAttachment.ATTACHMENT.ID;
    }

    @Override
    public Field<String> field2() {
        return JAttachment.ATTACHMENT.FILE_ID;
    }

    @Override
    public Field<String> field3() {
        return JAttachment.ATTACHMENT.THUMBNAIL_ID;
    }

    @Override
    public Field<String> field4() {
        return JAttachment.ATTACHMENT.CONTENT_TYPE;
    }

    @Override
    public Field<Long> field5() {
        return JAttachment.ATTACHMENT.PROJECT_ID;
    }

    @Override
    public Field<Long> field6() {
        return JAttachment.ATTACHMENT.LAUNCH_ID;
    }

    @Override
    public Field<Long> field7() {
        return JAttachment.ATTACHMENT.ITEM_ID;
    }

    @Override
    public Field<Long> field8() {
        return JAttachment.ATTACHMENT.FILE_SIZE;
    }

    @Override
    public Field<Timestamp> field9() {
        return JAttachment.ATTACHMENT.CREATION_DATE;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getFileId();
    }

    @Override
    public String component3() {
        return getThumbnailId();
    }

    @Override
    public String component4() {
        return getContentType();
    }

    @Override
    public Long component5() {
        return getProjectId();
    }

    @Override
    public Long component6() {
        return getLaunchId();
    }

    @Override
    public Long component7() {
        return getItemId();
    }

    @Override
    public Long component8() {
        return getFileSize();
    }

    @Override
    public Timestamp component9() {
        return getCreationDate();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getFileId();
    }

    @Override
    public String value3() {
        return getThumbnailId();
    }

    @Override
    public String value4() {
        return getContentType();
    }

    @Override
    public Long value5() {
        return getProjectId();
    }

    @Override
    public Long value6() {
        return getLaunchId();
    }

    @Override
    public Long value7() {
        return getItemId();
    }

    @Override
    public Long value8() {
        return getFileSize();
    }

    @Override
    public Timestamp value9() {
        return getCreationDate();
    }

    @Override
    public JAttachmentRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public JAttachmentRecord value2(String value) {
        setFileId(value);
        return this;
    }

    @Override
    public JAttachmentRecord value3(String value) {
        setThumbnailId(value);
        return this;
    }

    @Override
    public JAttachmentRecord value4(String value) {
        setContentType(value);
        return this;
    }

    @Override
    public JAttachmentRecord value5(Long value) {
        setProjectId(value);
        return this;
    }

    @Override
    public JAttachmentRecord value6(Long value) {
        setLaunchId(value);
        return this;
    }

    @Override
    public JAttachmentRecord value7(Long value) {
        setItemId(value);
        return this;
    }

    @Override
    public JAttachmentRecord value8(Long value) {
        setFileSize(value);
        return this;
    }

    @Override
    public JAttachmentRecord value9(Timestamp value) {
        setCreationDate(value);
        return this;
    }

    @Override
    public JAttachmentRecord values(Long value1, String value2, String value3, String value4, Long value5, Long value6, Long value7, Long value8, Timestamp value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JAttachmentRecord
     */
    public JAttachmentRecord() {
        super(JAttachment.ATTACHMENT);
    }

    /**
     * Create a detached, initialised JAttachmentRecord
     */
    public JAttachmentRecord(Long id, String fileId, String thumbnailId, String contentType, Long projectId, Long launchId, Long itemId, Long fileSize, Timestamp creationDate) {
        super(JAttachment.ATTACHMENT);

        set(0, id);
        set(1, fileId);
        set(2, thumbnailId);
        set(3, contentType);
        set(4, projectId);
        set(5, launchId);
        set(6, itemId);
        set(7, fileSize);
        set(8, creationDate);
    }
}
