/*
 *  Copyright (C) 2018 EPAM Systems
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/*
 * This file is generated by jOOQ.
 */
package com.epam.ta.reportportal.jooq.tables.records;


import com.epam.ta.reportportal.jooq.tables.JCrosstab4;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JCrosstab4Record extends TableRecordImpl<JCrosstab4Record> implements Record1<Object> {

    private static final long serialVersionUID = -1433146998;

    /**
     * Setter for <code>public.crosstab4.crosstab4</code>.
     */
    public void setCrosstab4(Object value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.crosstab4.crosstab4</code>.
     */
    public Object getCrosstab4() {
        return get(0);
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row1<Object> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row1<Object> valuesRow() {
        return (Row1) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Object> field1() {
        return JCrosstab4.CROSSTAB4.CROSSTAB4_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Object component1() {
        return getCrosstab4();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Object value1() {
        return getCrosstab4();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JCrosstab4Record value1(Object value) {
        setCrosstab4(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JCrosstab4Record values(Object value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JCrosstab4Record
     */
    public JCrosstab4Record() {
        super(JCrosstab4.CROSSTAB4);
    }

    /**
     * Create a detached, initialised JCrosstab4Record
     */
    public JCrosstab4Record(Object crosstab4) {
        super(JCrosstab4.CROSSTAB4);

        set(0, crosstab4);
    }
}
