/*
 * This file is generated by jOOQ.
*/
package com.epam.ta.reportportal.jooq.tables.records;

import com.epam.ta.reportportal.jooq.tables.JExecutionStatistics;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(value = { "http://www.jooq.org", "jOOQ version:3.10.5" }, comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JExecutionStatisticsRecord extends UpdatableRecordImpl<JExecutionStatisticsRecord>
		implements Record6<Long, Integer, String, Boolean, Long, Long> {

	private static final long serialVersionUID = -1034010907;

	/**
	 * Setter for <code>public.execution_statistics.es_id</code>.
	 */
	public void setEsId(Long value) {
		set(0, value);
	}

	/**
	 * Getter for <code>public.execution_statistics.es_id</code>.
	 */
	public Long getEsId() {
		return (Long) get(0);
	}

	/**
	 * Setter for <code>public.execution_statistics.es_counter</code>.
	 */
	public void setEsCounter(Integer value) {
		set(1, value);
	}

	/**
	 * Getter for <code>public.execution_statistics.es_counter</code>.
	 */
	public Integer getEsCounter() {
		return (Integer) get(1);
	}

	/**
	 * Setter for <code>public.execution_statistics.es_status</code>.
	 */
	public void setEsStatus(String value) {
		set(2, value);
	}

	/**
	 * Getter for <code>public.execution_statistics.es_status</code>.
	 */
	public String getEsStatus() {
		return (String) get(2);
	}

	/**
	 * Setter for <code>public.execution_statistics.positive</code>.
	 */
	public void setPositive(Boolean value) {
		set(3, value);
	}

	/**
	 * Getter for <code>public.execution_statistics.positive</code>.
	 */
	public Boolean getPositive() {
		return (Boolean) get(3);
	}

	/**
	 * Setter for <code>public.execution_statistics.item_id</code>.
	 */
	public void setItemId(Long value) {
		set(4, value);
	}

	/**
	 * Getter for <code>public.execution_statistics.item_id</code>.
	 */
	public Long getItemId() {
		return (Long) get(4);
	}

	/**
	 * Setter for <code>public.execution_statistics.launch_id</code>.
	 */
	public void setLaunchId(Long value) {
		set(5, value);
	}

	/**
	 * Getter for <code>public.execution_statistics.launch_id</code>.
	 */
	public Long getLaunchId() {
		return (Long) get(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Long> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Long, Integer, String, Boolean, Long, Long> fieldsRow() {
		return (Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Long, Integer, String, Boolean, Long, Long> valuesRow() {
		return (Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field1() {
		return JExecutionStatistics.EXECUTION_STATISTICS.ES_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return JExecutionStatistics.EXECUTION_STATISTICS.ES_COUNTER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return JExecutionStatistics.EXECUTION_STATISTICS.ES_STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Boolean> field4() {
		return JExecutionStatistics.EXECUTION_STATISTICS.POSITIVE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field5() {
		return JExecutionStatistics.EXECUTION_STATISTICS.ITEM_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field6() {
		return JExecutionStatistics.EXECUTION_STATISTICS.LAUNCH_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long component1() {
		return getEsId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer component2() {
		return getEsCounter();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String component3() {
		return getEsStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean component4() {
		return getPositive();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long component5() {
		return getItemId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long component6() {
		return getLaunchId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value1() {
		return getEsId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getEsCounter();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getEsStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean value4() {
		return getPositive();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value5() {
		return getItemId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value6() {
		return getLaunchId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public JExecutionStatisticsRecord value1(Long value) {
		setEsId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public JExecutionStatisticsRecord value2(Integer value) {
		setEsCounter(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public JExecutionStatisticsRecord value3(String value) {
		setEsStatus(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public JExecutionStatisticsRecord value4(Boolean value) {
		setPositive(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public JExecutionStatisticsRecord value5(Long value) {
		setItemId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public JExecutionStatisticsRecord value6(Long value) {
		setLaunchId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public JExecutionStatisticsRecord values(Long value1, Integer value2, String value3, Boolean value4, Long value5, Long value6) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached JExecutionStatisticsRecord
	 */
	public JExecutionStatisticsRecord() {
		super(JExecutionStatistics.EXECUTION_STATISTICS);
	}

	/**
	 * Create a detached, initialised JExecutionStatisticsRecord
	 */
	public JExecutionStatisticsRecord(Long esId, Integer esCounter, String esStatus, Boolean positive, Long itemId, Long launchId) {
		super(JExecutionStatistics.EXECUTION_STATISTICS);

		set(0, esId);
		set(1, esCounter);
		set(2, esStatus);
		set(3, positive);
		set(4, itemId);
		set(5, launchId);
	}
}
