/*
 * This file is generated by jOOQ.
 */
package com.epam.ta.reportportal.jooq.tables.records;


import com.epam.ta.reportportal.jooq.enums.JIntegrationAuthFlowEnum;
import com.epam.ta.reportportal.jooq.enums.JIntegrationGroupEnum;
import com.epam.ta.reportportal.jooq.tables.JIntegrationType;

import java.sql.Timestamp;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JIntegrationTypeRecord extends UpdatableRecordImpl<JIntegrationTypeRecord> implements Record7<Integer, String, JIntegrationAuthFlowEnum, Timestamp, JIntegrationGroupEnum, Boolean, JSONB> {

    private static final long serialVersionUID = -1999785253;

    /**
     * Setter for <code>public.integration_type.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.integration_type.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.integration_type.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.integration_type.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.integration_type.auth_flow</code>.
     */
    public void setAuthFlow(JIntegrationAuthFlowEnum value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.integration_type.auth_flow</code>.
     */
    public JIntegrationAuthFlowEnum getAuthFlow() {
        return (JIntegrationAuthFlowEnum) get(2);
    }

    /**
     * Setter for <code>public.integration_type.creation_date</code>.
     */
    public void setCreationDate(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.integration_type.creation_date</code>.
     */
    public Timestamp getCreationDate() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>public.integration_type.group_type</code>.
     */
    public void setGroupType(JIntegrationGroupEnum value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.integration_type.group_type</code>.
     */
    public JIntegrationGroupEnum getGroupType() {
        return (JIntegrationGroupEnum) get(4);
    }

    /**
     * Setter for <code>public.integration_type.enabled</code>.
     */
    public void setEnabled(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.integration_type.enabled</code>.
     */
    public Boolean getEnabled() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>public.integration_type.details</code>.
     */
    public void setDetails(JSONB value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.integration_type.details</code>.
     */
    public JSONB getDetails() {
        return (JSONB) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, String, JIntegrationAuthFlowEnum, Timestamp, JIntegrationGroupEnum, Boolean, JSONB> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, String, JIntegrationAuthFlowEnum, Timestamp, JIntegrationGroupEnum, Boolean, JSONB> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return JIntegrationType.INTEGRATION_TYPE.ID;
    }

    @Override
    public Field<String> field2() {
        return JIntegrationType.INTEGRATION_TYPE.NAME;
    }

    @Override
    public Field<JIntegrationAuthFlowEnum> field3() {
        return JIntegrationType.INTEGRATION_TYPE.AUTH_FLOW;
    }

    @Override
    public Field<Timestamp> field4() {
        return JIntegrationType.INTEGRATION_TYPE.CREATION_DATE;
    }

    @Override
    public Field<JIntegrationGroupEnum> field5() {
        return JIntegrationType.INTEGRATION_TYPE.GROUP_TYPE;
    }

    @Override
    public Field<Boolean> field6() {
        return JIntegrationType.INTEGRATION_TYPE.ENABLED;
    }

    @Override
    public Field<JSONB> field7() {
        return JIntegrationType.INTEGRATION_TYPE.DETAILS;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public JIntegrationAuthFlowEnum component3() {
        return getAuthFlow();
    }

    @Override
    public Timestamp component4() {
        return getCreationDate();
    }

    @Override
    public JIntegrationGroupEnum component5() {
        return getGroupType();
    }

    @Override
    public Boolean component6() {
        return getEnabled();
    }

    @Override
    public JSONB component7() {
        return getDetails();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public JIntegrationAuthFlowEnum value3() {
        return getAuthFlow();
    }

    @Override
    public Timestamp value4() {
        return getCreationDate();
    }

    @Override
    public JIntegrationGroupEnum value5() {
        return getGroupType();
    }

    @Override
    public Boolean value6() {
        return getEnabled();
    }

    @Override
    public JSONB value7() {
        return getDetails();
    }

    @Override
    public JIntegrationTypeRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public JIntegrationTypeRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public JIntegrationTypeRecord value3(JIntegrationAuthFlowEnum value) {
        setAuthFlow(value);
        return this;
    }

    @Override
    public JIntegrationTypeRecord value4(Timestamp value) {
        setCreationDate(value);
        return this;
    }

    @Override
    public JIntegrationTypeRecord value5(JIntegrationGroupEnum value) {
        setGroupType(value);
        return this;
    }

    @Override
    public JIntegrationTypeRecord value6(Boolean value) {
        setEnabled(value);
        return this;
    }

    @Override
    public JIntegrationTypeRecord value7(JSONB value) {
        setDetails(value);
        return this;
    }

    @Override
    public JIntegrationTypeRecord values(Integer value1, String value2, JIntegrationAuthFlowEnum value3, Timestamp value4, JIntegrationGroupEnum value5, Boolean value6, JSONB value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JIntegrationTypeRecord
     */
    public JIntegrationTypeRecord() {
        super(JIntegrationType.INTEGRATION_TYPE);
    }

    /**
     * Create a detached, initialised JIntegrationTypeRecord
     */
    public JIntegrationTypeRecord(Integer id, String name, JIntegrationAuthFlowEnum authFlow, Timestamp creationDate, JIntegrationGroupEnum groupType, Boolean enabled, JSONB details) {
        super(JIntegrationType.INTEGRATION_TYPE);

        set(0, id);
        set(1, name);
        set(2, authFlow);
        set(3, creationDate);
        set(4, groupType);
        set(5, enabled);
        set(6, details);
    }
}
