/*
 * This file is generated by jOOQ.
 */
package com.epam.ta.reportportal.jooq.tables.records;


import com.epam.ta.reportportal.jooq.tables.JLaunchNumber;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JLaunchNumberRecord extends UpdatableRecordImpl<JLaunchNumberRecord> implements Record4<Long, Long, String, Integer> {

    private static final long serialVersionUID = -1978268674;

    /**
     * Setter for <code>public.launch_number.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.launch_number.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.launch_number.project_id</code>.
     */
    public void setProjectId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.launch_number.project_id</code>.
     */
    public Long getProjectId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.launch_number.launch_name</code>.
     */
    public void setLaunchName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.launch_number.launch_name</code>.
     */
    public String getLaunchName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.launch_number.number</code>.
     */
    public void setNumber(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.launch_number.number</code>.
     */
    public Integer getNumber() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, Long, String, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Long, Long, String, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return JLaunchNumber.LAUNCH_NUMBER.ID;
    }

    @Override
    public Field<Long> field2() {
        return JLaunchNumber.LAUNCH_NUMBER.PROJECT_ID;
    }

    @Override
    public Field<String> field3() {
        return JLaunchNumber.LAUNCH_NUMBER.LAUNCH_NAME;
    }

    @Override
    public Field<Integer> field4() {
        return JLaunchNumber.LAUNCH_NUMBER.NUMBER;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getProjectId();
    }

    @Override
    public String component3() {
        return getLaunchName();
    }

    @Override
    public Integer component4() {
        return getNumber();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getProjectId();
    }

    @Override
    public String value3() {
        return getLaunchName();
    }

    @Override
    public Integer value4() {
        return getNumber();
    }

    @Override
    public JLaunchNumberRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public JLaunchNumberRecord value2(Long value) {
        setProjectId(value);
        return this;
    }

    @Override
    public JLaunchNumberRecord value3(String value) {
        setLaunchName(value);
        return this;
    }

    @Override
    public JLaunchNumberRecord value4(Integer value) {
        setNumber(value);
        return this;
    }

    @Override
    public JLaunchNumberRecord values(Long value1, Long value2, String value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JLaunchNumberRecord
     */
    public JLaunchNumberRecord() {
        super(JLaunchNumber.LAUNCH_NUMBER);
    }

    /**
     * Create a detached, initialised JLaunchNumberRecord
     */
    public JLaunchNumberRecord(Long id, Long projectId, String launchName, Integer number) {
        super(JLaunchNumber.LAUNCH_NUMBER);

        set(0, id);
        set(1, projectId);
        set(2, launchName);
        set(3, number);
    }
}
