/*
 * This file is generated by jOOQ.
 */
package com.epam.ta.reportportal.jooq.tables.records;


import com.epam.ta.reportportal.jooq.tables.JParameter;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JParameterRecord extends TableRecordImpl<JParameterRecord> implements Record3<Long, String, String> {

    private static final long serialVersionUID = 607314343;

    /**
     * Setter for <code>public.parameter.item_id</code>.
     */
    public void setItemId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.parameter.item_id</code>.
     */
    public Long getItemId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.parameter.key</code>.
     */
    public void setKey(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.parameter.key</code>.
     */
    public String getKey() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.parameter.value</code>.
     */
    public void setValue(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.parameter.value</code>.
     */
    public String getValue() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Long, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return JParameter.PARAMETER.ITEM_ID;
    }

    @Override
    public Field<String> field2() {
        return JParameter.PARAMETER.KEY;
    }

    @Override
    public Field<String> field3() {
        return JParameter.PARAMETER.VALUE;
    }

    @Override
    public Long component1() {
        return getItemId();
    }

    @Override
    public String component2() {
        return getKey();
    }

    @Override
    public String component3() {
        return getValue();
    }

    @Override
    public Long value1() {
        return getItemId();
    }

    @Override
    public String value2() {
        return getKey();
    }

    @Override
    public String value3() {
        return getValue();
    }

    @Override
    public JParameterRecord value1(Long value) {
        setItemId(value);
        return this;
    }

    @Override
    public JParameterRecord value2(String value) {
        setKey(value);
        return this;
    }

    @Override
    public JParameterRecord value3(String value) {
        setValue(value);
        return this;
    }

    @Override
    public JParameterRecord values(Long value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JParameterRecord
     */
    public JParameterRecord() {
        super(JParameter.PARAMETER);
    }

    /**
     * Create a detached, initialised JParameterRecord
     */
    public JParameterRecord(Long itemId, String key, String value) {
        super(JParameter.PARAMETER);

        set(0, itemId);
        set(1, key);
        set(2, value);
    }
}
