/*
 * This file is generated by jOOQ.
 */
package com.epam.ta.reportportal.jooq.tables.records;


import com.epam.ta.reportportal.jooq.tables.JPlaginMarketplace;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class JPlaginMarketplaceRecord extends UpdatableRecordImpl<JPlaginMarketplaceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.plagin_marketplace.name</code>.
     */
    public void setName(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.plagin_marketplace.name</code>.
     */
    public String getName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.plagin_marketplace.uri</code>.
     */
    public void setUri(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.plagin_marketplace.uri</code>.
     */
    public String getUri() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JPlaginMarketplaceRecord
     */
    public JPlaginMarketplaceRecord() {
        super(JPlaginMarketplace.PLAGIN_MARKETPLACE);
    }

    /**
     * Create a detached, initialised JPlaginMarketplaceRecord
     */
    public JPlaginMarketplaceRecord(String name, String uri) {
        super(JPlaginMarketplace.PLAGIN_MARKETPLACE);

        setName(name);
        setUri(uri);
        resetChangedOnNotNull();
    }
}
