/*
 * This file is generated by jOOQ.
 */
package com.epam.ta.reportportal.jooq.tables.records;


import com.epam.ta.reportportal.jooq.enums.JTestItemTypeEnum;
import com.epam.ta.reportportal.jooq.tables.JTestItem;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JTestItemRecord extends UpdatableRecordImpl<JTestItemRecord> implements Record14<Long, String, JTestItemTypeEnum, Timestamp, String, Timestamp, Object, String, Boolean, Boolean, Boolean, Long, Long, Long> {

    private static final long serialVersionUID = 844454120;

    /**
     * Setter for <code>public.test_item.item_id</code>.
     */
    public void setItemId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.test_item.item_id</code>.
     */
    public Long getItemId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.test_item.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.test_item.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.test_item.type</code>.
     */
    public void setType(JTestItemTypeEnum value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.test_item.type</code>.
     */
    public JTestItemTypeEnum getType() {
        return (JTestItemTypeEnum) get(2);
    }

    /**
     * Setter for <code>public.test_item.start_time</code>.
     */
    public void setStartTime(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.test_item.start_time</code>.
     */
    public Timestamp getStartTime() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>public.test_item.description</code>.
     */
    public void setDescription(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.test_item.description</code>.
     */
    public String getDescription() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.test_item.last_modified</code>.
     */
    public void setLastModified(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.test_item.last_modified</code>.
     */
    public Timestamp getLastModified() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>public.test_item.path</code>.
     */
    public void setPath(Object value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.test_item.path</code>.
     */
    public Object getPath() {
        return get(6);
    }

    /**
     * Setter for <code>public.test_item.unique_id</code>.
     */
    public void setUniqueId(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.test_item.unique_id</code>.
     */
    public String getUniqueId() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.test_item.has_children</code>.
     */
    public void setHasChildren(Boolean value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.test_item.has_children</code>.
     */
    public Boolean getHasChildren() {
        return (Boolean) get(8);
    }

    /**
     * Setter for <code>public.test_item.has_retries</code>.
     */
    public void setHasRetries(Boolean value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.test_item.has_retries</code>.
     */
    public Boolean getHasRetries() {
        return (Boolean) get(9);
    }

    /**
     * Setter for <code>public.test_item.has_stats</code>.
     */
    public void setHasStats(Boolean value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.test_item.has_stats</code>.
     */
    public Boolean getHasStats() {
        return (Boolean) get(10);
    }

    /**
     * Setter for <code>public.test_item.parent_id</code>.
     */
    public void setParentId(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.test_item.parent_id</code>.
     */
    public Long getParentId() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>public.test_item.retry_of</code>.
     */
    public void setRetryOf(Long value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.test_item.retry_of</code>.
     */
    public Long getRetryOf() {
        return (Long) get(12);
    }

    /**
     * Setter for <code>public.test_item.launch_id</code>.
     */
    public void setLaunchId(Long value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.test_item.launch_id</code>.
     */
    public Long getLaunchId() {
        return (Long) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<Long, String, JTestItemTypeEnum, Timestamp, String, Timestamp, Object, String, Boolean, Boolean, Boolean, Long, Long, Long> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<Long, String, JTestItemTypeEnum, Timestamp, String, Timestamp, Object, String, Boolean, Boolean, Boolean, Long, Long, Long> valuesRow() {
        return (Row14) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return JTestItem.TEST_ITEM.ITEM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return JTestItem.TEST_ITEM.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<JTestItemTypeEnum> field3() {
        return JTestItem.TEST_ITEM.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return JTestItem.TEST_ITEM.START_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return JTestItem.TEST_ITEM.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return JTestItem.TEST_ITEM.LAST_MODIFIED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Object> field7() {
        return JTestItem.TEST_ITEM.PATH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return JTestItem.TEST_ITEM.UNIQUE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field9() {
        return JTestItem.TEST_ITEM.HAS_CHILDREN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field10() {
        return JTestItem.TEST_ITEM.HAS_RETRIES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field11() {
        return JTestItem.TEST_ITEM.HAS_STATS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field12() {
        return JTestItem.TEST_ITEM.PARENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field13() {
        return JTestItem.TEST_ITEM.RETRY_OF;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field14() {
        return JTestItem.TEST_ITEM.LAUNCH_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getItemId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JTestItemTypeEnum component3() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getStartTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getLastModified();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Object component7() {
        return getPath();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getUniqueId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component9() {
        return getHasChildren();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component10() {
        return getHasRetries();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component11() {
        return getHasStats();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component12() {
        return getParentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component13() {
        return getRetryOf();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component14() {
        return getLaunchId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getItemId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JTestItemTypeEnum value3() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getStartTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getLastModified();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Object value7() {
        return getPath();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getUniqueId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value9() {
        return getHasChildren();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value10() {
        return getHasRetries();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value11() {
        return getHasStats();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value12() {
        return getParentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value13() {
        return getRetryOf();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value14() {
        return getLaunchId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JTestItemRecord value1(Long value) {
        setItemId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JTestItemRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JTestItemRecord value3(JTestItemTypeEnum value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JTestItemRecord value4(Timestamp value) {
        setStartTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JTestItemRecord value5(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JTestItemRecord value6(Timestamp value) {
        setLastModified(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JTestItemRecord value7(Object value) {
        setPath(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JTestItemRecord value8(String value) {
        setUniqueId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JTestItemRecord value9(Boolean value) {
        setHasChildren(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JTestItemRecord value10(Boolean value) {
        setHasRetries(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JTestItemRecord value11(Boolean value) {
        setHasStats(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JTestItemRecord value12(Long value) {
        setParentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JTestItemRecord value13(Long value) {
        setRetryOf(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JTestItemRecord value14(Long value) {
        setLaunchId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JTestItemRecord values(Long value1, String value2, JTestItemTypeEnum value3, Timestamp value4, String value5, Timestamp value6, Object value7, String value8, Boolean value9, Boolean value10, Boolean value11, Long value12, Long value13, Long value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JTestItemRecord
     */
    public JTestItemRecord() {
        super(JTestItem.TEST_ITEM);
    }

    /**
     * Create a detached, initialised JTestItemRecord
     */
    public JTestItemRecord(Long itemId, String name, JTestItemTypeEnum type, Timestamp startTime, String description, Timestamp lastModified, Object path, String uniqueId, Boolean hasChildren, Boolean hasRetries, Boolean hasStats, Long parentId, Long retryOf, Long launchId) {
        super(JTestItem.TEST_ITEM);

        set(0, itemId);
        set(1, name);
        set(2, type);
        set(3, startTime);
        set(4, description);
        set(5, lastModified);
        set(6, path);
        set(7, uniqueId);
        set(8, hasChildren);
        set(9, hasRetries);
        set(10, hasStats);
        set(11, parentId);
        set(12, retryOf);
        set(13, launchId);
    }
}
