/*
 * This file is generated by jOOQ.
 */
package com.epam.ta.reportportal.jooq.tables.records;


import com.epam.ta.reportportal.jooq.tables.JUserCreationBid;

import java.time.Instant;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JUserCreationBidRecord extends UpdatableRecordImpl<JUserCreationBidRecord> implements Record5<String, Instant, String, Long, JSONB> {

    private static final long serialVersionUID = -1036772641;

    /**
     * Setter for <code>public.user_creation_bid.uuid</code>.
     */
    public void setUuid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.user_creation_bid.uuid</code>.
     */
    public String getUuid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.user_creation_bid.last_modified</code>.
     */
    public void setLastModified(Instant value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.user_creation_bid.last_modified</code>.
     */
    public Instant getLastModified() {
        return (Instant) get(1);
    }

    /**
     * Setter for <code>public.user_creation_bid.email</code>.
     */
    public void setEmail(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.user_creation_bid.email</code>.
     */
    public String getEmail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.user_creation_bid.inviting_user_id</code>.
     */
    public void setInvitingUserId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.user_creation_bid.inviting_user_id</code>.
     */
    public Long getInvitingUserId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.user_creation_bid.metadata</code>.
     */
    public void setMetadata(JSONB value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.user_creation_bid.metadata</code>.
     */
    public JSONB getMetadata() {
        return (JSONB) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<String, Instant, String, Long, JSONB> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<String, Instant, String, Long, JSONB> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return JUserCreationBid.USER_CREATION_BID.UUID;
    }

    @Override
    public Field<Instant> field2() {
        return JUserCreationBid.USER_CREATION_BID.LAST_MODIFIED;
    }

    @Override
    public Field<String> field3() {
        return JUserCreationBid.USER_CREATION_BID.EMAIL;
    }

    @Override
    public Field<Long> field4() {
        return JUserCreationBid.USER_CREATION_BID.INVITING_USER_ID;
    }

    @Override
    public Field<JSONB> field5() {
        return JUserCreationBid.USER_CREATION_BID.METADATA;
    }

    @Override
    public String component1() {
        return getUuid();
    }

    @Override
    public Instant component2() {
        return getLastModified();
    }

    @Override
    public String component3() {
        return getEmail();
    }

    @Override
    public Long component4() {
        return getInvitingUserId();
    }

    @Override
    public JSONB component5() {
        return getMetadata();
    }

    @Override
    public String value1() {
        return getUuid();
    }

    @Override
    public Instant value2() {
        return getLastModified();
    }

    @Override
    public String value3() {
        return getEmail();
    }

    @Override
    public Long value4() {
        return getInvitingUserId();
    }

    @Override
    public JSONB value5() {
        return getMetadata();
    }

    @Override
    public JUserCreationBidRecord value1(String value) {
        setUuid(value);
        return this;
    }

    @Override
    public JUserCreationBidRecord value2(Instant value) {
        setLastModified(value);
        return this;
    }

    @Override
    public JUserCreationBidRecord value3(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public JUserCreationBidRecord value4(Long value) {
        setInvitingUserId(value);
        return this;
    }

    @Override
    public JUserCreationBidRecord value5(JSONB value) {
        setMetadata(value);
        return this;
    }

    @Override
    public JUserCreationBidRecord values(String value1, Instant value2, String value3, Long value4, JSONB value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JUserCreationBidRecord
     */
    public JUserCreationBidRecord() {
        super(JUserCreationBid.USER_CREATION_BID);
    }

    /**
     * Create a detached, initialised JUserCreationBidRecord
     */
    public JUserCreationBidRecord(String uuid, Instant lastModified, String email, Long invitingUserId, JSONB metadata) {
        super(JUserCreationBid.USER_CREATION_BID);

        set(0, uuid);
        set(1, lastModified);
        set(2, email);
        set(3, invitingUserId);
        set(4, metadata);
    }
}
