/*
 * This file is generated by jOOQ.
*/
package com.epam.ta.reportportal.jooq.tables.records;

import com.epam.ta.reportportal.jooq.enums.ProjectRoleEnum;
import com.epam.ta.reportportal.jooq.tables.ProjectUser;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProjectUserRecord extends UpdatableRecordImpl<ProjectUserRecord> implements Record3<Integer, Integer, ProjectRoleEnum> {

    private static final long serialVersionUID = 403719043;

    /**
     * Setter for <code>public.project_user.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.project_user.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.project_user.project_id</code>.
     */
    public void setProjectId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.project_user.project_id</code>.
     */
    public Integer getProjectId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.project_user.project_role</code>.
     */
    public void setProjectRole(ProjectRoleEnum value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.project_user.project_role</code>.
     */
    public ProjectRoleEnum getProjectRole() {
        return (ProjectRoleEnum) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, ProjectRoleEnum> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, ProjectRoleEnum> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return ProjectUser.PROJECT_USER.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return ProjectUser.PROJECT_USER.PROJECT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ProjectRoleEnum> field3() {
        return ProjectUser.PROJECT_USER.PROJECT_ROLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getProjectId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectRoleEnum component3() {
        return getProjectRole();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getProjectId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectRoleEnum value3() {
        return getProjectRole();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectUserRecord value1(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectUserRecord value2(Integer value) {
        setProjectId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectUserRecord value3(ProjectRoleEnum value) {
        setProjectRole(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProjectUserRecord values(Integer value1, Integer value2, ProjectRoleEnum value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProjectUserRecord
     */
    public ProjectUserRecord() {
        super(ProjectUser.PROJECT_USER);
    }

    /**
     * Create a detached, initialised ProjectUserRecord
     */
    public ProjectUserRecord(Integer userId, Integer projectId, ProjectRoleEnum projectRole) {
        super(ProjectUser.PROJECT_USER);

        set(0, userId);
        set(1, projectId);
        set(2, projectRole);
    }
}
