/*
 * This file is generated by jOOQ.
 */
package com.epam.ta.reportportal.jooq.tables;


import com.epam.ta.reportportal.jooq.Indexes;
import com.epam.ta.reportportal.jooq.JPublic;
import com.epam.ta.reportportal.jooq.Keys;
import com.epam.ta.reportportal.jooq.tables.records.JApiKeysRecord;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.LocalDateAsLocalDateTimeBinding;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JApiKeys extends TableImpl<JApiKeysRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.api_keys</code>
     */
    public static final JApiKeys API_KEYS = new JApiKeys();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JApiKeysRecord> getRecordType() {
        return JApiKeysRecord.class;
    }

    /**
     * The column <code>public.api_keys.id</code>.
     */
    public final TableField<JApiKeysRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.api_keys.name</code>.
     */
    public final TableField<JApiKeysRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.api_keys.hash</code>.
     */
    public final TableField<JApiKeysRecord, String> HASH = createField(DSL.name("hash"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.api_keys.created_at</code>.
     */
    public final TableField<JApiKeysRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>public.api_keys.user_id</code>.
     */
    public final TableField<JApiKeysRecord, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.api_keys.last_used_at</code>.
     */
    public final TableField<JApiKeysRecord, LocalDateTime> LAST_USED_AT = createField(DSL.name("last_used_at"), SQLDataType.LOCALDATETIME(0), this, "", new LocalDateAsLocalDateTimeBinding());

    private JApiKeys(Name alias, Table<JApiKeysRecord> aliased) {
        this(alias, aliased, null);
    }

    private JApiKeys(Name alias, Table<JApiKeysRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.api_keys</code> table reference
     */
    public JApiKeys(String alias) {
        this(DSL.name(alias), API_KEYS);
    }

    /**
     * Create an aliased <code>public.api_keys</code> table reference
     */
    public JApiKeys(Name alias) {
        this(alias, API_KEYS);
    }

    /**
     * Create a <code>public.api_keys</code> table reference
     */
    public JApiKeys() {
        this(DSL.name("api_keys"), null);
    }

    public <O extends Record> JApiKeys(Table<O> child, ForeignKey<O, JApiKeysRecord> key) {
        super(child, key, API_KEYS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : JPublic.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.HASH_API_KEYS_IDX);
    }

    @Override
    public Identity<JApiKeysRecord, Long> getIdentity() {
        return (Identity<JApiKeysRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<JApiKeysRecord> getPrimaryKey() {
        return Keys.API_KEYS_PKEY;
    }

    @Override
    public List<UniqueKey<JApiKeysRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.USERS_API_KEYS_UNIQUE);
    }

    @Override
    public List<ForeignKey<JApiKeysRecord, ?>> getReferences() {
        return Arrays.asList(Keys.API_KEYS__API_KEYS_USER_ID_FKEY);
    }

    private transient JUsers _users;

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    public JUsers users() {
        if (_users == null)
            _users = new JUsers(this, Keys.API_KEYS__API_KEYS_USER_ID_FKEY);

        return _users;
    }

    @Override
    public JApiKeys as(String alias) {
        return new JApiKeys(DSL.name(alias), this);
    }

    @Override
    public JApiKeys as(Name alias) {
        return new JApiKeys(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public JApiKeys rename(String name) {
        return new JApiKeys(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public JApiKeys rename(Name name) {
        return new JApiKeys(name, null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, String, String, LocalDateTime, Long, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }
}
