/*
 * This file is generated by jOOQ.
 */
package com.epam.ta.reportportal.jooq.tables;


import com.epam.ta.reportportal.jooq.Indexes;
import com.epam.ta.reportportal.jooq.JPublic;
import com.epam.ta.reportportal.jooq.Keys;
import com.epam.ta.reportportal.jooq.tables.records.JImportantLaunchRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row1;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JImportantLaunch extends TableImpl<JImportantLaunchRecord> {

    private static final long serialVersionUID = 1013657604;

    /**
     * The reference instance of <code>public.important_launch</code>
     */
    public static final JImportantLaunch IMPORTANT_LAUNCH = new JImportantLaunch();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JImportantLaunchRecord> getRecordType() {
        return JImportantLaunchRecord.class;
    }

    /**
     * The column <code>public.important_launch.launch_id</code>.
     */
    public final TableField<JImportantLaunchRecord, Long> LAUNCH_ID = createField(DSL.name("launch_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>public.important_launch</code> table reference
     */
    public JImportantLaunch() {
        this(DSL.name("important_launch"), null);
    }

    /**
     * Create an aliased <code>public.important_launch</code> table reference
     */
    public JImportantLaunch(String alias) {
        this(DSL.name(alias), IMPORTANT_LAUNCH);
    }

    /**
     * Create an aliased <code>public.important_launch</code> table reference
     */
    public JImportantLaunch(Name alias) {
        this(alias, IMPORTANT_LAUNCH);
    }

    private JImportantLaunch(Name alias, Table<JImportantLaunchRecord> aliased) {
        this(alias, aliased, null);
    }

    private JImportantLaunch(Name alias, Table<JImportantLaunchRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> JImportantLaunch(Table<O> child, ForeignKey<O, JImportantLaunchRecord> key) {
        super(child, key, IMPORTANT_LAUNCH);
    }

    @Override
    public Schema getSchema() {
        return JPublic.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.IMPORTANT_LAUNCH_PKEY);
    }

    @Override
    public UniqueKey<JImportantLaunchRecord> getPrimaryKey() {
        return Keys.IMPORTANT_LAUNCH_PKEY;
    }

    @Override
    public List<UniqueKey<JImportantLaunchRecord>> getKeys() {
        return Arrays.<UniqueKey<JImportantLaunchRecord>>asList(Keys.IMPORTANT_LAUNCH_PKEY);
    }

    @Override
    public List<ForeignKey<JImportantLaunchRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<JImportantLaunchRecord, ?>>asList(Keys.IMPORTANT_LAUNCH__IMPORTANT_LAUNCH_LAUNCH_ID_FKEY);
    }

    public JLaunch launch() {
        return new JLaunch(this, Keys.IMPORTANT_LAUNCH__IMPORTANT_LAUNCH_LAUNCH_ID_FKEY);
    }

    @Override
    public JImportantLaunch as(String alias) {
        return new JImportantLaunch(DSL.name(alias), this);
    }

    @Override
    public JImportantLaunch as(Name alias) {
        return new JImportantLaunch(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public JImportantLaunch rename(String name) {
        return new JImportantLaunch(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public JImportantLaunch rename(Name name) {
        return new JImportantLaunch(name, null);
    }

    // -------------------------------------------------------------------------
    // Row1 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row1<Long> fieldsRow() {
        return (Row1) super.fieldsRow();
    }
}
