/*
 * This file is generated by jOOQ.
 */
package com.epam.ta.reportportal.jooq.tables;


import com.epam.ta.reportportal.jooq.Indexes;
import com.epam.ta.reportportal.jooq.JPublic;
import com.epam.ta.reportportal.jooq.Keys;
import com.epam.ta.reportportal.jooq.tables.records.JIssueTypeProjectRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JIssueTypeProject extends TableImpl<JIssueTypeProjectRecord> {

    private static final long serialVersionUID = -184496297;

    /**
     * The reference instance of <code>public.issue_type_project</code>
     */
    public static final JIssueTypeProject ISSUE_TYPE_PROJECT = new JIssueTypeProject();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JIssueTypeProjectRecord> getRecordType() {
        return JIssueTypeProjectRecord.class;
    }

    /**
     * The column <code>public.issue_type_project.project_id</code>.
     */
    public final TableField<JIssueTypeProjectRecord, Long> PROJECT_ID = createField(DSL.name("project_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.issue_type_project.issue_type_id</code>.
     */
    public final TableField<JIssueTypeProjectRecord, Long> ISSUE_TYPE_ID = createField(DSL.name("issue_type_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>public.issue_type_project</code> table reference
     */
    public JIssueTypeProject() {
        this(DSL.name("issue_type_project"), null);
    }

    /**
     * Create an aliased <code>public.issue_type_project</code> table reference
     */
    public JIssueTypeProject(String alias) {
        this(DSL.name(alias), ISSUE_TYPE_PROJECT);
    }

    /**
     * Create an aliased <code>public.issue_type_project</code> table reference
     */
    public JIssueTypeProject(Name alias) {
        this(alias, ISSUE_TYPE_PROJECT);
    }

    private JIssueTypeProject(Name alias, Table<JIssueTypeProjectRecord> aliased) {
        this(alias, aliased, null);
    }

    private JIssueTypeProject(Name alias, Table<JIssueTypeProjectRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> JIssueTypeProject(Table<O> child, ForeignKey<O, JIssueTypeProjectRecord> key) {
        super(child, key, ISSUE_TYPE_PROJECT);
    }

    @Override
    public Schema getSchema() {
        return JPublic.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ISSUE_TYPE_PROJECT_PK);
    }

    @Override
    public UniqueKey<JIssueTypeProjectRecord> getPrimaryKey() {
        return Keys.ISSUE_TYPE_PROJECT_PK;
    }

    @Override
    public List<UniqueKey<JIssueTypeProjectRecord>> getKeys() {
        return Arrays.<UniqueKey<JIssueTypeProjectRecord>>asList(Keys.ISSUE_TYPE_PROJECT_PK);
    }

    @Override
    public List<ForeignKey<JIssueTypeProjectRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<JIssueTypeProjectRecord, ?>>asList(Keys.ISSUE_TYPE_PROJECT__ISSUE_TYPE_PROJECT_PROJECT_ID_FKEY, Keys.ISSUE_TYPE_PROJECT__ISSUE_TYPE_PROJECT_ISSUE_TYPE_ID_FKEY);
    }

    public JProject project() {
        return new JProject(this, Keys.ISSUE_TYPE_PROJECT__ISSUE_TYPE_PROJECT_PROJECT_ID_FKEY);
    }

    public JIssueType issueType() {
        return new JIssueType(this, Keys.ISSUE_TYPE_PROJECT__ISSUE_TYPE_PROJECT_ISSUE_TYPE_ID_FKEY);
    }

    @Override
    public JIssueTypeProject as(String alias) {
        return new JIssueTypeProject(DSL.name(alias), this);
    }

    @Override
    public JIssueTypeProject as(Name alias) {
        return new JIssueTypeProject(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public JIssueTypeProject rename(String name) {
        return new JIssueTypeProject(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public JIssueTypeProject rename(Name name) {
        return new JIssueTypeProject(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
