/*
 * This file is generated by jOOQ.
*/
package com.epam.ta.reportportal.jooq.tables;


import com.epam.ta.reportportal.jooq.Indexes;
import com.epam.ta.reportportal.jooq.JPublic;
import com.epam.ta.reportportal.jooq.Keys;
import com.epam.ta.reportportal.jooq.tables.records.JLdapSynchronizationAttributesRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JLdapSynchronizationAttributes extends TableImpl<JLdapSynchronizationAttributesRecord> {

    private static final long serialVersionUID = -639577716;

    /**
     * The reference instance of <code>public.ldap_synchronization_attributes</code>
     */
    public static final JLdapSynchronizationAttributes LDAP_SYNCHRONIZATION_ATTRIBUTES = new JLdapSynchronizationAttributes();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JLdapSynchronizationAttributesRecord> getRecordType() {
        return JLdapSynchronizationAttributesRecord.class;
    }

    /**
     * The column <code>public.ldap_synchronization_attributes.id</code>.
     */
    public final TableField<JLdapSynchronizationAttributesRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('ldap_synchronization_attributes_id_seq'::regclass)", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.ldap_synchronization_attributes.email</code>.
     */
    public final TableField<JLdapSynchronizationAttributesRecord, String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR(256), this, "");

    /**
     * The column <code>public.ldap_synchronization_attributes.full_name</code>.
     */
    public final TableField<JLdapSynchronizationAttributesRecord, String> FULL_NAME = createField("full_name", org.jooq.impl.SQLDataType.VARCHAR(256), this, "");

    /**
     * The column <code>public.ldap_synchronization_attributes.photo</code>.
     */
    public final TableField<JLdapSynchronizationAttributesRecord, String> PHOTO = createField("photo", org.jooq.impl.SQLDataType.VARCHAR(128), this, "");

    /**
     * Create a <code>public.ldap_synchronization_attributes</code> table reference
     */
    public JLdapSynchronizationAttributes() {
        this(DSL.name("ldap_synchronization_attributes"), null);
    }

    /**
     * Create an aliased <code>public.ldap_synchronization_attributes</code> table reference
     */
    public JLdapSynchronizationAttributes(String alias) {
        this(DSL.name(alias), LDAP_SYNCHRONIZATION_ATTRIBUTES);
    }

    /**
     * Create an aliased <code>public.ldap_synchronization_attributes</code> table reference
     */
    public JLdapSynchronizationAttributes(Name alias) {
        this(alias, LDAP_SYNCHRONIZATION_ATTRIBUTES);
    }

    private JLdapSynchronizationAttributes(Name alias, Table<JLdapSynchronizationAttributesRecord> aliased) {
        this(alias, aliased, null);
    }

    private JLdapSynchronizationAttributes(Name alias, Table<JLdapSynchronizationAttributesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return JPublic.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.LDAP_SYNCHRONIZATION_ATTRIBUTES_EMAIL_KEY, Indexes.LDAP_SYNCHRONIZATION_ATTRIBUTES_PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<JLdapSynchronizationAttributesRecord, Long> getIdentity() {
        return Keys.IDENTITY_LDAP_SYNCHRONIZATION_ATTRIBUTES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<JLdapSynchronizationAttributesRecord> getPrimaryKey() {
        return Keys.LDAP_SYNCHRONIZATION_ATTRIBUTES_PK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<JLdapSynchronizationAttributesRecord>> getKeys() {
        return Arrays.<UniqueKey<JLdapSynchronizationAttributesRecord>>asList(Keys.LDAP_SYNCHRONIZATION_ATTRIBUTES_PK, Keys.LDAP_SYNCHRONIZATION_ATTRIBUTES_EMAIL_KEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JLdapSynchronizationAttributes as(String alias) {
        return new JLdapSynchronizationAttributes(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JLdapSynchronizationAttributes as(Name alias) {
        return new JLdapSynchronizationAttributes(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public JLdapSynchronizationAttributes rename(String name) {
        return new JLdapSynchronizationAttributes(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public JLdapSynchronizationAttributes rename(Name name) {
        return new JLdapSynchronizationAttributes(name, null);
    }
}
