/*
 * This file is generated by jOOQ.
 */
package com.epam.ta.reportportal.jooq.tables;


import com.epam.ta.reportportal.jooq.Indexes;
import com.epam.ta.reportportal.jooq.JPublic;
import com.epam.ta.reportportal.jooq.Keys;
import com.epam.ta.reportportal.jooq.tables.records.JLogRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Check;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row11;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JLog extends TableImpl<JLogRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.log</code>
     */
    public static final JLog LOG = new JLog();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JLogRecord> getRecordType() {
        return JLogRecord.class;
    }

    /**
     * The column <code>public.log.id</code>.
     */
    public final TableField<JLogRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.log.uuid</code>.
     */
    public final TableField<JLogRecord, String> UUID = createField(DSL.name("uuid"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>public.log.log_time</code>.
     */
    public final TableField<JLogRecord, LocalDateTime> LOG_TIME = createField(DSL.name("log_time"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>public.log.log_message</code>.
     */
    public final TableField<JLogRecord, String> LOG_MESSAGE = createField(DSL.name("log_message"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.log.item_id</code>.
     */
    public final TableField<JLogRecord, Long> ITEM_ID = createField(DSL.name("item_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.log.launch_id</code>.
     */
    public final TableField<JLogRecord, Long> LAUNCH_ID = createField(DSL.name("launch_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.log.last_modified</code>.
     */
    public final TableField<JLogRecord, LocalDateTime> LAST_MODIFIED = createField(DSL.name("last_modified"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>public.log.log_level</code>.
     */
    public final TableField<JLogRecord, Integer> LOG_LEVEL = createField(DSL.name("log_level"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.log.attachment_id</code>.
     */
    public final TableField<JLogRecord, Long> ATTACHMENT_ID = createField(DSL.name("attachment_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.log.project_id</code>.
     */
    public final TableField<JLogRecord, Long> PROJECT_ID = createField(DSL.name("project_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.log.cluster_id</code>.
     */
    public final TableField<JLogRecord, Long> CLUSTER_ID = createField(DSL.name("cluster_id"), SQLDataType.BIGINT, this, "");

    private JLog(Name alias, Table<JLogRecord> aliased) {
        this(alias, aliased, null);
    }

    private JLog(Name alias, Table<JLogRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.log</code> table reference
     */
    public JLog(String alias) {
        this(DSL.name(alias), LOG);
    }

    /**
     * Create an aliased <code>public.log</code> table reference
     */
    public JLog(Name alias) {
        this(alias, LOG);
    }

    /**
     * Create a <code>public.log</code> table reference
     */
    public JLog() {
        this(DSL.name("log"), null);
    }

    public <O extends Record> JLog(Table<O> child, ForeignKey<O, JLogRecord> key) {
        super(child, key, LOG);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : JPublic.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.LOG_ATTACH_ID_IDX, Indexes.LOG_CLUSTER_IDX, Indexes.LOG_LAUNCH_ID_IDX, Indexes.LOG_PROJECT_ID_LOG_TIME_IDX, Indexes.LOG_PROJECT_IDX, Indexes.LOG_TI_IDX);
    }

    @Override
    public Identity<JLogRecord, Long> getIdentity() {
        return (Identity<JLogRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<JLogRecord> getPrimaryKey() {
        return Keys.LOG_PK;
    }

    @Override
    public List<ForeignKey<JLogRecord, ?>> getReferences() {
        return Arrays.asList(Keys.LOG__LOG_ITEM_ID_FKEY, Keys.LOG__LOG_LAUNCH_ID_FKEY, Keys.LOG__LOG_ATTACHMENT_ID_FKEY);
    }

    private transient JTestItem _testItem;
    private transient JLaunch _launch;
    private transient JAttachment _attachment;

    /**
     * Get the implicit join path to the <code>public.test_item</code> table.
     */
    public JTestItem testItem() {
        if (_testItem == null)
            _testItem = new JTestItem(this, Keys.LOG__LOG_ITEM_ID_FKEY);

        return _testItem;
    }

    /**
     * Get the implicit join path to the <code>public.launch</code> table.
     */
    public JLaunch launch() {
        if (_launch == null)
            _launch = new JLaunch(this, Keys.LOG__LOG_LAUNCH_ID_FKEY);

        return _launch;
    }

    /**
     * Get the implicit join path to the <code>public.attachment</code> table.
     */
    public JAttachment attachment() {
        if (_attachment == null)
            _attachment = new JAttachment(this, Keys.LOG__LOG_ATTACHMENT_ID_FKEY);

        return _attachment;
    }

    @Override
    public List<Check<JLogRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("log_check"), "((((item_id IS NOT NULL) AND (launch_id IS NULL)) OR ((item_id IS NULL) AND (launch_id IS NOT NULL))))", true)
        );
    }

    @Override
    public JLog as(String alias) {
        return new JLog(DSL.name(alias), this);
    }

    @Override
    public JLog as(Name alias) {
        return new JLog(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public JLog rename(String name) {
        return new JLog(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public JLog rename(Name name) {
        return new JLog(name, null);
    }

    // -------------------------------------------------------------------------
    // Row11 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row11<Long, String, LocalDateTime, String, Long, Long, LocalDateTime, Integer, Long, Long, Long> fieldsRow() {
        return (Row11) super.fieldsRow();
    }
}
