/*
 * This file is generated by jOOQ.
 */
package com.epam.ta.reportportal.jooq.tables;


import com.epam.ta.reportportal.jooq.Indexes;
import com.epam.ta.reportportal.jooq.JPublic;
import com.epam.ta.reportportal.jooq.Keys;
import com.epam.ta.reportportal.jooq.tables.records.JOauthAccessTokenRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row9;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JOauthAccessToken extends TableImpl<JOauthAccessTokenRecord> {

    private static final long serialVersionUID = -1465585063;

    /**
     * The reference instance of <code>public.oauth_access_token</code>
     */
    public static final JOauthAccessToken OAUTH_ACCESS_TOKEN = new JOauthAccessToken();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JOauthAccessTokenRecord> getRecordType() {
        return JOauthAccessTokenRecord.class;
    }

    /**
     * The column <code>public.oauth_access_token.id</code>.
     */
    public final TableField<JOauthAccessTokenRecord, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('oauth_access_token_id_seq'::regclass)", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.oauth_access_token.token_id</code>.
     */
    public final TableField<JOauthAccessTokenRecord, String> TOKEN_ID = createField(DSL.name("token_id"), org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.oauth_access_token.token</code>.
     */
    public final TableField<JOauthAccessTokenRecord, byte[]> TOKEN = createField(DSL.name("token"), org.jooq.impl.SQLDataType.BLOB, this, "");

    /**
     * The column <code>public.oauth_access_token.authentication_id</code>.
     */
    public final TableField<JOauthAccessTokenRecord, String> AUTHENTICATION_ID = createField(DSL.name("authentication_id"), org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.oauth_access_token.username</code>.
     */
    public final TableField<JOauthAccessTokenRecord, String> USERNAME = createField(DSL.name("username"), org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.oauth_access_token.user_id</code>.
     */
    public final TableField<JOauthAccessTokenRecord, Long> USER_ID = createField(DSL.name("user_id"), org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.oauth_access_token.client_id</code>.
     */
    public final TableField<JOauthAccessTokenRecord, String> CLIENT_ID = createField(DSL.name("client_id"), org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.oauth_access_token.authentication</code>.
     */
    public final TableField<JOauthAccessTokenRecord, byte[]> AUTHENTICATION = createField(DSL.name("authentication"), org.jooq.impl.SQLDataType.BLOB, this, "");

    /**
     * The column <code>public.oauth_access_token.refresh_token</code>.
     */
    public final TableField<JOauthAccessTokenRecord, String> REFRESH_TOKEN = createField(DSL.name("refresh_token"), org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * Create a <code>public.oauth_access_token</code> table reference
     */
    public JOauthAccessToken() {
        this(DSL.name("oauth_access_token"), null);
    }

    /**
     * Create an aliased <code>public.oauth_access_token</code> table reference
     */
    public JOauthAccessToken(String alias) {
        this(DSL.name(alias), OAUTH_ACCESS_TOKEN);
    }

    /**
     * Create an aliased <code>public.oauth_access_token</code> table reference
     */
    public JOauthAccessToken(Name alias) {
        this(alias, OAUTH_ACCESS_TOKEN);
    }

    private JOauthAccessToken(Name alias, Table<JOauthAccessTokenRecord> aliased) {
        this(alias, aliased, null);
    }

    private JOauthAccessToken(Name alias, Table<JOauthAccessTokenRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> JOauthAccessToken(Table<O> child, ForeignKey<O, JOauthAccessTokenRecord> key) {
        super(child, key, OAUTH_ACCESS_TOKEN);
    }

    @Override
    public Schema getSchema() {
        return JPublic.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.OAUTH_ACCESS_TOKEN_PKEY, Indexes.OAUTH_AT_USER_IDX, Indexes.USERS_ACCESS_TOKEN_UNIQUE);
    }

    @Override
    public Identity<JOauthAccessTokenRecord, Long> getIdentity() {
        return Keys.IDENTITY_OAUTH_ACCESS_TOKEN;
    }

    @Override
    public UniqueKey<JOauthAccessTokenRecord> getPrimaryKey() {
        return Keys.OAUTH_ACCESS_TOKEN_PKEY;
    }

    @Override
    public List<UniqueKey<JOauthAccessTokenRecord>> getKeys() {
        return Arrays.<UniqueKey<JOauthAccessTokenRecord>>asList(Keys.OAUTH_ACCESS_TOKEN_PKEY, Keys.USERS_ACCESS_TOKEN_UNIQUE);
    }

    @Override
    public List<ForeignKey<JOauthAccessTokenRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<JOauthAccessTokenRecord, ?>>asList(Keys.OAUTH_ACCESS_TOKEN__OAUTH_ACCESS_TOKEN_USER_ID_FKEY);
    }

    public JUsers users() {
        return new JUsers(this, Keys.OAUTH_ACCESS_TOKEN__OAUTH_ACCESS_TOKEN_USER_ID_FKEY);
    }

    @Override
    public JOauthAccessToken as(String alias) {
        return new JOauthAccessToken(DSL.name(alias), this);
    }

    @Override
    public JOauthAccessToken as(Name alias) {
        return new JOauthAccessToken(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public JOauthAccessToken rename(String name) {
        return new JOauthAccessToken(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public JOauthAccessToken rename(Name name) {
        return new JOauthAccessToken(name, null);
    }

    // -------------------------------------------------------------------------
    // Row9 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row9<Long, String, byte[], String, String, Long, String, byte[], String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }
}
