/*
 * This file is generated by jOOQ.
 */
package com.epam.ta.reportportal.jooq.tables;


import com.epam.ta.reportportal.jooq.JPublic;
import com.epam.ta.reportportal.jooq.Keys;
import com.epam.ta.reportportal.jooq.tables.records.JPatternTemplateRecord;
import java.util.Arrays;
import java.util.List;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JPatternTemplate extends TableImpl<JPatternTemplateRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.pattern_template</code>
     */
    public static final JPatternTemplate PATTERN_TEMPLATE = new JPatternTemplate();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JPatternTemplateRecord> getRecordType() {
        return JPatternTemplateRecord.class;
    }

    /**
     * The column <code>public.pattern_template.id</code>.
     */
    public final TableField<JPatternTemplateRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.pattern_template.name</code>.
     */
    public final TableField<JPatternTemplateRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.pattern_template.value</code>.
     */
    public final TableField<JPatternTemplateRecord, String> VALUE = createField(DSL.name("value"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.pattern_template.type</code>.
     */
    public final TableField<JPatternTemplateRecord, String> TYPE = createField(DSL.name("type"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.pattern_template.enabled</code>.
     */
    public final TableField<JPatternTemplateRecord, Boolean> ENABLED = createField(DSL.name("enabled"), SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>public.pattern_template.project_id</code>.
     */
    public final TableField<JPatternTemplateRecord, Long> PROJECT_ID = createField(DSL.name("project_id"), SQLDataType.BIGINT.nullable(false), this, "");

    private JPatternTemplate(Name alias, Table<JPatternTemplateRecord> aliased) {
        this(alias, aliased, null);
    }

    private JPatternTemplate(Name alias, Table<JPatternTemplateRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.pattern_template</code> table reference
     */
    public JPatternTemplate(String alias) {
        this(DSL.name(alias), PATTERN_TEMPLATE);
    }

    /**
     * Create an aliased <code>public.pattern_template</code> table reference
     */
    public JPatternTemplate(Name alias) {
        this(alias, PATTERN_TEMPLATE);
    }

    /**
     * Create a <code>public.pattern_template</code> table reference
     */
    public JPatternTemplate() {
        this(DSL.name("pattern_template"), null);
    }

    public <O extends Record> JPatternTemplate(Table<O> child, ForeignKey<O, JPatternTemplateRecord> key) {
        super(child, key, PATTERN_TEMPLATE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : JPublic.PUBLIC;
    }

    @Override
    public Identity<JPatternTemplateRecord, Long> getIdentity() {
        return (Identity<JPatternTemplateRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<JPatternTemplateRecord> getPrimaryKey() {
        return Keys.PATTERN_TEMPLATE_PK;
    }

    @Override
    public List<UniqueKey<JPatternTemplateRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UNQ_NAME_PROJECTID);
    }

    @Override
    public List<ForeignKey<JPatternTemplateRecord, ?>> getReferences() {
        return Arrays.asList(Keys.PATTERN_TEMPLATE__PATTERN_TEMPLATE_PROJECT_ID_FKEY);
    }

    private transient JProject _project;

    /**
     * Get the implicit join path to the <code>public.project</code> table.
     */
    public JProject project() {
        if (_project == null)
            _project = new JProject(this, Keys.PATTERN_TEMPLATE__PATTERN_TEMPLATE_PROJECT_ID_FKEY);

        return _project;
    }

    @Override
    public JPatternTemplate as(String alias) {
        return new JPatternTemplate(DSL.name(alias), this);
    }

    @Override
    public JPatternTemplate as(Name alias) {
        return new JPatternTemplate(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public JPatternTemplate rename(String name) {
        return new JPatternTemplate(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public JPatternTemplate rename(Name name) {
        return new JPatternTemplate(name, null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, String, String, String, Boolean, Long> fieldsRow() {
        return (Row6) super.fieldsRow();
    }
}
