/*
 * This file is generated by jOOQ.
 */
package com.epam.ta.reportportal.jooq.tables;


import com.epam.ta.reportportal.jooq.JPublic;
import com.epam.ta.reportportal.jooq.Keys;
import com.epam.ta.reportportal.jooq.tables.records.JWidgetFilterRecord;
import java.util.Arrays;
import java.util.List;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JWidgetFilter extends TableImpl<JWidgetFilterRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.widget_filter</code>
     */
    public static final JWidgetFilter WIDGET_FILTER = new JWidgetFilter();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JWidgetFilterRecord> getRecordType() {
        return JWidgetFilterRecord.class;
    }

    /**
     * The column <code>public.widget_filter.widget_id</code>.
     */
    public final TableField<JWidgetFilterRecord, Long> WIDGET_ID = createField(DSL.name("widget_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.widget_filter.filter_id</code>.
     */
    public final TableField<JWidgetFilterRecord, Long> FILTER_ID = createField(DSL.name("filter_id"), SQLDataType.BIGINT.nullable(false), this, "");

    private JWidgetFilter(Name alias, Table<JWidgetFilterRecord> aliased) {
        this(alias, aliased, null);
    }

    private JWidgetFilter(Name alias, Table<JWidgetFilterRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.widget_filter</code> table reference
     */
    public JWidgetFilter(String alias) {
        this(DSL.name(alias), WIDGET_FILTER);
    }

    /**
     * Create an aliased <code>public.widget_filter</code> table reference
     */
    public JWidgetFilter(Name alias) {
        this(alias, WIDGET_FILTER);
    }

    /**
     * Create a <code>public.widget_filter</code> table reference
     */
    public JWidgetFilter() {
        this(DSL.name("widget_filter"), null);
    }

    public <O extends Record> JWidgetFilter(Table<O> child, ForeignKey<O, JWidgetFilterRecord> key) {
        super(child, key, WIDGET_FILTER);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : JPublic.PUBLIC;
    }

    @Override
    public UniqueKey<JWidgetFilterRecord> getPrimaryKey() {
        return Keys.WIDGET_FILTER_PK;
    }

    @Override
    public List<ForeignKey<JWidgetFilterRecord, ?>> getReferences() {
        return Arrays.asList(Keys.WIDGET_FILTER__WIDGET_FILTER_WIDGET_ID_FKEY, Keys.WIDGET_FILTER__WIDGET_FILTER_FILTER_ID_FKEY);
    }

    private transient JWidget _widget;
    private transient JFilter _filter;

    /**
     * Get the implicit join path to the <code>public.widget</code> table.
     */
    public JWidget widget() {
        if (_widget == null)
            _widget = new JWidget(this, Keys.WIDGET_FILTER__WIDGET_FILTER_WIDGET_ID_FKEY);

        return _widget;
    }

    /**
     * Get the implicit join path to the <code>public.filter</code> table.
     */
    public JFilter filter() {
        if (_filter == null)
            _filter = new JFilter(this, Keys.WIDGET_FILTER__WIDGET_FILTER_FILTER_ID_FKEY);

        return _filter;
    }

    @Override
    public JWidgetFilter as(String alias) {
        return new JWidgetFilter(DSL.name(alias), this);
    }

    @Override
    public JWidgetFilter as(Name alias) {
        return new JWidgetFilter(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public JWidgetFilter rename(String name) {
        return new JWidgetFilter(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public JWidgetFilter rename(Name name) {
        return new JWidgetFilter(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
