/*
 * This file is generated by jOOQ.
 */
package com.epam.ta.reportportal.jooq;


import com.epam.ta.reportportal.jooq.tables.*;
import com.epam.ta.reportportal.jooq.tables.records.JPgpArmorHeadersRecord;
import org.jooq.Configuration;
import org.jooq.Field;
import org.jooq.Result;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.acl_class</code>.
     */
    public static final JAclClass ACL_CLASS = JAclClass.ACL_CLASS;

    /**
     * The table <code>public.acl_entry</code>.
     */
    public static final JAclEntry ACL_ENTRY = JAclEntry.ACL_ENTRY;

    /**
     * The table <code>public.acl_object_identity</code>.
     */
    public static final JAclObjectIdentity ACL_OBJECT_IDENTITY = JAclObjectIdentity.ACL_OBJECT_IDENTITY;

    /**
     * The table <code>public.acl_sid</code>.
     */
    public static final JAclSid ACL_SID = JAclSid.ACL_SID;

    /**
     * The table <code>public.activity</code>.
     */
    public static final JActivity ACTIVITY = JActivity.ACTIVITY;

    /**
     * The table <code>public.attachment</code>.
     */
    public static final JAttachment ATTACHMENT = JAttachment.ATTACHMENT;

    /**
     * The table <code>public.attribute</code>.
     */
    public static final JAttribute ATTRIBUTE = JAttribute.ATTRIBUTE;

    /**
     * The table <code>public.clusters</code>.
     */
    public static final JClusters CLUSTERS = JClusters.CLUSTERS;

    /**
     * The table <code>public.content_field</code>.
     */
    public static final JContentField CONTENT_FIELD = JContentField.CONTENT_FIELD;

    /**
     * The table <code>public.dashboard</code>.
     */
    public static final JDashboard DASHBOARD = JDashboard.DASHBOARD;

    /**
     * The table <code>public.dashboard_widget</code>.
     */
    public static final JDashboardWidget DASHBOARD_WIDGET = JDashboardWidget.DASHBOARD_WIDGET;

    /**
     * The table <code>public.filter</code>.
     */
    public static final JFilter FILTER = JFilter.FILTER;

    /**
     * The table <code>public.filter_condition</code>.
     */
    public static final JFilterCondition FILTER_CONDITION = JFilterCondition.FILTER_CONDITION;

    /**
     * The table <code>public.filter_sort</code>.
     */
    public static final JFilterSort FILTER_SORT = JFilterSort.FILTER_SORT;

    /**
     * The table <code>public.integration</code>.
     */
    public static final JIntegration INTEGRATION = JIntegration.INTEGRATION;

    /**
     * The table <code>public.integration_type</code>.
     */
    public static final JIntegrationType INTEGRATION_TYPE = JIntegrationType.INTEGRATION_TYPE;

    /**
     * The table <code>public.issue</code>.
     */
    public static final JIssue ISSUE = JIssue.ISSUE;

    /**
     * The table <code>public.issue_group</code>.
     */
    public static final JIssueGroup ISSUE_GROUP = JIssueGroup.ISSUE_GROUP;

    /**
     * The table <code>public.issue_ticket</code>.
     */
    public static final JIssueTicket ISSUE_TICKET = JIssueTicket.ISSUE_TICKET;

    /**
     * The table <code>public.issue_type</code>.
     */
    public static final JIssueType ISSUE_TYPE = JIssueType.ISSUE_TYPE;

    /**
     * The table <code>public.issue_type_project</code>.
     */
    public static final JIssueTypeProject ISSUE_TYPE_PROJECT = JIssueTypeProject.ISSUE_TYPE_PROJECT;

    /**
     * The table <code>public.item_attribute</code>.
     */
    public static final JItemAttribute ITEM_ATTRIBUTE = JItemAttribute.ITEM_ATTRIBUTE;

    /**
     * The table <code>public.launch</code>.
     */
    public static final JLaunch LAUNCH = JLaunch.LAUNCH;

    /**
     * The table <code>public.launch_attribute_rules</code>.
     */
    public static final JLaunchAttributeRules LAUNCH_ATTRIBUTE_RULES = JLaunchAttributeRules.LAUNCH_ATTRIBUTE_RULES;

    /**
     * The table <code>public.launch_names</code>.
     */
    public static final JLaunchNames LAUNCH_NAMES = JLaunchNames.LAUNCH_NAMES;

    /**
     * The table <code>public.launch_number</code>.
     */
    public static final JLaunchNumber LAUNCH_NUMBER = JLaunchNumber.LAUNCH_NUMBER;

    /**
     * The table <code>public.log</code>.
     */
    public static final JLog LOG = JLog.LOG;

    /**
     * The table <code>public.oauth_access_token</code>.
     */
    public static final JOauthAccessToken OAUTH_ACCESS_TOKEN = JOauthAccessToken.OAUTH_ACCESS_TOKEN;

    /**
     * The table <code>public.oauth_registration</code>.
     */
    public static final JOauthRegistration OAUTH_REGISTRATION = JOauthRegistration.OAUTH_REGISTRATION;

    /**
     * The table <code>public.oauth_registration_restriction</code>.
     */
    public static final JOauthRegistrationRestriction OAUTH_REGISTRATION_RESTRICTION = JOauthRegistrationRestriction.OAUTH_REGISTRATION_RESTRICTION;

    /**
     * The table <code>public.oauth_registration_scope</code>.
     */
    public static final JOauthRegistrationScope OAUTH_REGISTRATION_SCOPE = JOauthRegistrationScope.OAUTH_REGISTRATION_SCOPE;

    /**
     * The table <code>public.onboarding</code>.
     */
    public static final JOnboarding ONBOARDING = JOnboarding.ONBOARDING;

    /**
     * The table <code>public.parameter</code>.
     */
    public static final JParameter PARAMETER = JParameter.PARAMETER;

    /**
     * The table <code>public.pattern_template</code>.
     */
    public static final JPatternTemplate PATTERN_TEMPLATE = JPatternTemplate.PATTERN_TEMPLATE;

    /**
     * The table <code>public.pattern_template_test_item</code>.
     */
    public static final JPatternTemplateTestItem PATTERN_TEMPLATE_TEST_ITEM = JPatternTemplateTestItem.PATTERN_TEMPLATE_TEST_ITEM;

    /**
     * The table <code>public.pgp_armor_headers</code>.
     */
    public static final JPgpArmorHeaders PGP_ARMOR_HEADERS = JPgpArmorHeaders.PGP_ARMOR_HEADERS;

    /**
     * Call <code>public.pgp_armor_headers</code>.
     */
    public static Result<JPgpArmorHeadersRecord> PGP_ARMOR_HEADERS(Configuration configuration, String __1) {
        return configuration.dsl().selectFrom(com.epam.ta.reportportal.jooq.tables.JPgpArmorHeaders.PGP_ARMOR_HEADERS.call(__1)).fetch();
    }

    /**
     * Get <code>public.pgp_armor_headers</code> as a table.
     */
    public static JPgpArmorHeaders PGP_ARMOR_HEADERS(String __1) {
        return com.epam.ta.reportportal.jooq.tables.JPgpArmorHeaders.PGP_ARMOR_HEADERS.call(__1);
    }

    /**
     * Get <code>public.pgp_armor_headers</code> as a table.
     */
    public static JPgpArmorHeaders PGP_ARMOR_HEADERS(Field<String> __1) {
        return com.epam.ta.reportportal.jooq.tables.JPgpArmorHeaders.PGP_ARMOR_HEADERS.call(__1);
    }

    /**
     * The table <code>public.project</code>.
     */
    public static final JProject PROJECT = JProject.PROJECT;

    /**
     * The table <code>public.project_attribute</code>.
     */
    public static final JProjectAttribute PROJECT_ATTRIBUTE = JProjectAttribute.PROJECT_ATTRIBUTE;

    /**
     * The table <code>public.project_user</code>.
     */
    public static final JProjectUser PROJECT_USER = JProjectUser.PROJECT_USER;

    /**
     * The table <code>public.recipients</code>.
     */
    public static final JRecipients RECIPIENTS = JRecipients.RECIPIENTS;

    /**
     * The table <code>public.restore_password_bid</code>.
     */
    public static final JRestorePasswordBid RESTORE_PASSWORD_BID = JRestorePasswordBid.RESTORE_PASSWORD_BID;

    /**
     * The table <code>public.sender_case</code>.
     */
    public static final JSenderCase SENDER_CASE = JSenderCase.SENDER_CASE;

    /**
     * The table <code>public.server_settings</code>.
     */
    public static final JServerSettings SERVER_SETTINGS = JServerSettings.SERVER_SETTINGS;

    /**
     * The table <code>public.shareable_entity</code>.
     */
    public static final JShareableEntity SHAREABLE_ENTITY = JShareableEntity.SHAREABLE_ENTITY;

    /**
     * The table <code>public.statistics</code>.
     */
    public static final JStatistics STATISTICS = JStatistics.STATISTICS;

    /**
     * The table <code>public.statistics_field</code>.
     */
    public static final JStatisticsField STATISTICS_FIELD = JStatisticsField.STATISTICS_FIELD;

    /**
     * The table <code>public.test_item</code>.
     */
    public static final JTestItem TEST_ITEM = JTestItem.TEST_ITEM;

    /**
     * The table <code>public.test_item_results</code>.
     */
    public static final JTestItemResults TEST_ITEM_RESULTS = JTestItemResults.TEST_ITEM_RESULTS;

    /**
     * The table <code>public.ticket</code>.
     */
    public static final JTicket TICKET = JTicket.TICKET;

    /**
     * The table <code>public.user_creation_bid</code>.
     */
    public static final JUserCreationBid USER_CREATION_BID = JUserCreationBid.USER_CREATION_BID;

    /**
     * The table <code>public.user_preference</code>.
     */
    public static final JUserPreference USER_PREFERENCE = JUserPreference.USER_PREFERENCE;

    /**
     * The table <code>public.users</code>.
     */
    public static final JUsers USERS = JUsers.USERS;

    /**
     * The table <code>public.widget</code>.
     */
    public static final JWidget WIDGET = JWidget.WIDGET;

    /**
     * The table <code>public.widget_filter</code>.
     */
    public static final JWidgetFilter WIDGET_FILTER = JWidgetFilter.WIDGET_FILTER;
}
