ALTER SEQUENCE statistics_field_sf_id_seq
  RESTART WITH 1;
DELETE FROM statistics_field;
ALTER SEQUENCE statistics_s_id_seq
  RESTART WITH 1;
DELETE FROM statistics;
DELETE FROM test_item_results;
ALTER SEQUENCE test_item_item_id_seq
  RESTART WITH 1;
DELETE FROM test_item;